# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../nbs/01_cli.ipynb #8d265033
from fastcore.script import call_parse
from pathlib import Path
from .core import RunPython

import asyncio

# %% ../nbs/01_cli.ipynb #9d8e45dd
@call_parse
def main(path: str):
    "Run a python script file in the safepyrun sandbox"
    pyrun = RunPython()
    asyncio.run(pyrun(Path(path).read_text()))
