"""Docs: https://AnswerDotAI.github.io/safepyrun/cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../nbs/01_cli.ipynb #8d265033
from fastcore.script import call_parse
from typing import Annotated
from pathlib import Path
from .core import RunPython

import asyncio, sys

# %% ../nbs/01_cli.ipynb #e9eea171
@call_parse
def main(path: Annotated[str, "Path to script, or '-' for stdin", dict(opt=False, nargs='?', default='-')]):
    "Run a python script file in the safepyrun sandbox"
    try:
        code = sys.stdin.read() if path == '-' else Path(path).read_text()
        if (r := asyncio.run(RunPython()(code))) is not None: print(r)
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
