# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto #0
__all__ = ['main']

# %% ../nbs/01_cli.ipynb #8d265033
from fastcore.script import call_parse
from pathlib import Path
from .core import RunPython

import asyncio, sys

# %% ../nbs/01_cli.ipynb #e9eea171
@call_parse
def main(path: str='-'):
    "Run a python script file in the safepyrun sandbox"
    try:
        code = sys.stdin.read() if path == '-' else Path(path).read_text()
        result = asyncio.run(RunPython()(code))
        if result is not None: print(result)
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
