# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['all_builtins', 'ALLOWED_DUNDERS', 'default_ok_dests', 'find_var', 'allow', 'chk_dest', 'WritePolicy',
           'PosWritePolicy', 'PathWritePolicy', 'OpenWritePolicy', 'allow_write_types', 'sdir', 'SafeTransformer',
           'RunPython', 'create_pyrun_magic', 'doc', 'allow_matplotlib', 'load_ipython_extension']

# %% ../nbs/00_core.ipynb #468aa264
from fastcore.utils import *
from fastcore.xtras import asdict
from fastcore.xdg import xdg_config_home
from fastcore.docments import MarkdownRenderer
from inspect import currentframe,Parameter,signature
from contextvars import ContextVar

import json,importlib,linecache,re,inspect,uuid,ast,warnings,collections,time,asyncio,urllib.parse,dataclasses,shlex,urllib
import zlib,unicodedata,binascii,enum,secrets,pickle,contextlib,types,keyword,httpx,operator
import heapq, bisect, html, struct, decimal, fractions, pprint, fnmatch, base64
import random, statistics, difflib, csv, string, textwrap, hashlib, copy, datetime as dt_mod
import xml.etree.ElementTree as ET,ipaddress,colorsys,cmath,traceback,sys,shutil
from datetime import datetime
from urllib.parse import quote,unquote,urlencode
from io import StringIO,BytesIO
from collections import Counter,deque,OrderedDict
from IPython.display import display,HTML,Markdown,Image,Pretty,SVG
from types import SimpleNamespace
from re import Pattern

# %% ../nbs/00_core.ipynb #f178e529
from fastcore.imports import __llmtools__
from fastcore.test import expect_fail,test_eq
from RestrictedPython import utility_builtins, safe_builtins,limited_builtins
from RestrictedPython.transformer import RestrictingNodeTransformer, INSPECT_ATTRIBUTES, copy_locations
from restrictedpython_async import *

# %% ../nbs/00_core.ipynb #16c25d79
# ContextVar fallback for when stack walking fails (e.g. inside asyncio.gather)
_rp_globals = ContextVar('_rp_globals', default=None)

def _find_frame_dict(sentinel:str):
    "Find the globals dict containing sentinel, or calling frame's globals if no sentinel"
    frame = currentframe().f_back.f_back
    if not sentinel: return frame.f_globals
    while frame:
        if sentinel in frame.f_globals: return frame.f_globals
        frame = frame.f_back
    # Fall back to RunPython globals stored in ContextVar (e.g. from asyncio.gather)
    rpg = _rp_globals.get()
    if rpg and sentinel in rpg: return rpg
    return globals()


# %% ../nbs/00_core.ipynb #99383e45
def find_var(var:str):
    "Search for var in all frames of the call stack"
    return _find_frame_dict(var)[var]

# %% ../nbs/00_core.ipynb #947e6c21
__pytools__ = collections.defaultdict(set)

def _name_in(s, name):
    if ... in s or name in s: return True
    return any(isinstance(x, tuple) and x[0] == name for x in s)

def _get_policy(s, name):
    for x in s:
        if isinstance(x, tuple) and x[0] == name: return x[1]
    return None

def _cls_ok(obj, name):
    for o in [obj] + list(type(obj).__mro__):
        try: s = __pytools__.get(o)
        except TypeError: continue
        if s and _name_in(s, name): return True
    return False

def allow(*c, write_policy=None):
    def _wrap(v):
        if write_policy is None or v is ... or isinstance(v, tuple): return v
        return (v, write_policy)
    for o in c:
        if isinstance(o, dict):
            for k,v in o.items(): __pytools__[k].update(_wrap(x) for x in listify(v))
        else:
            mod = sys.modules.get(getattr(o, '__module__', '__main__'), sys.modules.get('__main__'))
            __pytools__[mod].add(_wrap(o.__name__))
    if len(c)==1 and callable(c[0]): return c[0]


# %% ../nbs/00_core.ipynb #eb580254
def chk_dest(p, ok_dests):
    resolved = str(Path(p).resolve())
    if not any(resolved == (rd := str(Path(d).expanduser().resolve())) or resolved.startswith(rd + '/') for d in ok_dests):
        raise PermissionError(f"Write to '{p}' not allowed; permitted: {ok_dests}")

# %% ../nbs/00_core.ipynb #8146b916
class WritePolicy:
    "Base for write destination policies"
    def __call__(self, obj, args, kwargs, ok_dests): raise NotImplementedError

class PosWritePolicy(WritePolicy):
    "Check positional/keyword arg is an allowed write destination"
    def __init__(self, pos=0, kw=None): store_attr()
    def __call__(self, obj, args, kwargs, ok_dests):
        p = kwargs.get(self.kw) if self.kw and self.kw in kwargs else args[self.pos] if self.pos < len(args) else None
        if p is not None: chk_dest(p, ok_dests)

class PathWritePolicy(WritePolicy):
    "Check resolved Path self, optionally also target args"
    def __init__(self, target_pos=None, target_kw=None): store_attr()
    def __call__(self, obj, args, kwargs, ok_dests):
        chk_dest(obj, ok_dests)
        if self.target_pos is not None and self.target_pos < len(args): chk_dest(args[self.target_pos], ok_dests)
        if self.target_kw and self.target_kw in kwargs: chk_dest(kwargs[self.target_kw], ok_dests)

class OpenWritePolicy(WritePolicy):
    "Check open() only when mode is writable"
    def __call__(self, obj, args, kwargs, ok_dests):
        mode = kwargs.get('mode', args[1] if len(args) > 1 else 'r')
        if any(c in mode for c in 'wax+'): chk_dest(args[0] if args else kwargs.get('file'), ok_dests)

# %% ../nbs/00_core.ipynb #b0f8587e
__pytools_write_types__ = set()

def allow_write_types(*types):
    "Allow in-place mutation of instances of these types (and their subclasses via isinstance)"
    __pytools_write_types__.update(types)

class _WriteGuard:
    "Proxy that allows item/attr mutation but blocks setting attrs to callables"
    def __init__(self, obj): object.__setattr__(self, '_obj', obj)
    def _chk_globals(self):
        o = object.__getattribute__(self, '_obj')
        if isinstance(o, dict) and '__builtins__' in o:
            raise PermissionError("Cannot mutate globals/frame dicts")
    def __setattr__(self, name, val):
        if callable(val): raise PermissionError(f"Setting attribute '{name}' to a callable is not allowed")
        setattr(object.__getattribute__(self, '_obj'), name, val)
    def __delattr__(self, name): delattr(object.__getattribute__(self, '_obj'), name)
    def __setitem__(self, key, val):
        self._chk_globals()
        object.__getattribute__(self, '_obj')[key] = val
    def __delitem__(self, key):
        self._chk_globals()
        del object.__getattribute__(self, '_obj')[key]

def _default_write_(obj):
    "Guard for in-place mutation; allows only registered types, blocks setting attrs to callables"
    if isinstance(obj, tuple(__pytools_write_types__)): return _WriteGuard(obj)
    raise PermissionError(f"Write to {type(obj).__name__} not allowed in sandbox")

# %% ../nbs/00_core.ipynb #703cdc90
class _WriteChecked:
    "Wrap a method to enforce its WritePolicy before calling"
    def __init__(self, obj, method, policy, ok_dests): self.obj,self.method,self.policy,self.ok_dests = obj,method,policy,ok_dests
    def __call__(self, *args, **kwargs):
        self.policy(self.obj, args, kwargs, self.ok_dests)
        return self.method(*args, **kwargs)

# %% ../nbs/00_core.ipynb #2a097981
_open_policy = OpenWritePolicy()

def _safe_open(ok_dests):
    def _open(*args, **kwargs):
        _open_policy(None, args, kwargs, ok_dests)
        return open(*args, **kwargs)
    return _open

# %% ../nbs/00_core.ipynb #fee6c11b
def sdir(o): return [a for a in dir(o) if not a.startswith('_')]

all_builtins = safe_builtins | utility_builtins | limited_builtins | async_builtins | dict(
    dict=dict, list=list, set=set, tuple=tuple, frozenset=frozenset,
    __import__=__import__,
    iter=iter, next=next, hasattr=hasattr,
    help=help, dir=sdir, sum=sum
)

# %% ../nbs/00_core.ipynb #069afe1c
def _get_write_policy(obj, name):
    for o in [obj] + list(type(obj).__mro__):
        try: s = __pytools__.get(o)
        except TypeError: continue
        if s:
            p = _get_policy(s, name)
            if p is not None: return p
    return None

def _make_safe_getattr(ok_dests=None):
    def _safe_getattr(obj, name):
        val = getattr(obj, name)
        if callable(val):
            if ok_dests is not None:
                p = _get_write_policy(obj, name)
                if p is not None: return _WriteChecked(obj, val, p, ok_dests)
            if not _cls_ok(obj, name):
                keys = [f"{cls.__name__}.{name}" for cls in type(obj).__mro__]
                keys += [f"{cls.__module__}.{cls.__qualname__}.{name}" for cls in type(obj).__mro__ if hasattr(cls, '__module__')]
                obj_name = getattr(obj, '__name__', None)
                if obj_name: keys.append(f"{obj_name}.{name}")
                if not any(k in __llmtools__ for k in keys): raise AttributeError(f"Cannot access callable: {name}")
        return val
    return _safe_getattr


# %% ../nbs/00_core.ipynb #6becac3b
class _DirectPrint:
    def __init__(self, *a, **kw): pass
    def _call_print(self, *a, **kw): print(*a, **kw)
    def __call__(self, *a, **kw): print(*a, **kw)

# %% ../nbs/00_core.ipynb #6eeed34a
class _Uncallable:
    def __init__(self, o, name):
        functools.update_wrapper(self, o)
        self._o,self._name = o,name
    def __call__(self, *a, **kw): raise PermissionError(f"Calling `{self._name}` is not permitted")
    def __getattr__(self, name): return getattr(self._o, name)
    def __repr__(self): return repr(self._o)

def _callable_ok(k, v):
    if k in __llmtools__: return True
    if v in __pytools__: return True
    if any(c in __pytools__ for c in type(v).__mro__): return True
    mod = sys.modules.get(getattr(v, '__module__', None))
    if mod and _cls_ok(mod, getattr(v, '__qualname__', k)): return True
    return False


# %% ../nbs/00_core.ipynb #3e4ede6c
ALLOWED_DUNDERS = {'__name__', '__module__', '__doc__', '__qualname__', '__file__'}

class SafeTransformer(RestrictingNodeTransformer):
    def visit_Attribute(self, node):
        if node.attr.startswith('_') and node.attr != '_' and node.attr not in ALLOWED_DUNDERS:
            self.error(node, f'"{node.attr}" is an invalid attribute name because it starts with "_".')
        if node.attr.endswith('__roles__'):
            self.error(node, f'"{node.attr}" is an invalid attribute name because it ends with "__roles__".')
        if node.attr in INSPECT_ATTRIBUTES:
            self.error(node, f'"{node.attr}" is a restricted name, that is forbidden to access in RestrictedPython.')
        if isinstance(node.ctx, ast.Load):
            node = self.node_contents_visit(node)
            new_node = ast.Call(func=ast.Name('_getattr_', ast.Load()), args=[node.value, ast.Constant(node.attr)], keywords=[])
            copy_locations(new_node, node)
            return new_node
        elif isinstance(node.ctx, (ast.Store, ast.Del)):
            node = self.node_contents_visit(node)
            new_value = ast.Call(func=ast.Name('_write_', ast.Load()), args=[node.value], keywords=[])
            copy_locations(new_value, node.value)
            node.value = new_value
            return node
        else: raise NotImplementedError(f"Unknown ctx type: {type(node.ctx)}")

# %% ../nbs/00_core.ipynb #e8365db0
_inplace_ops = {
    '+=': operator.iadd, '-=': operator.isub, '*=': operator.imul,
    '/=': operator.itruediv, '//=': operator.ifloordiv, '%=': operator.imod,
    '**=': operator.ipow, '<<=': operator.ilshift, '>>=': operator.irshift,
    '&=': operator.iand, '|=': operator.ior, '^=': operator.ixor,
    '@=': operator.imatmul,
}

def _inplacevar_(op, x, y): return _inplace_ops[op](x, y)
def _safe_type(o:object): return type(o)

# %% ../nbs/00_core.ipynb #55cc6157
async def _run_python(code:str, g=None, ok_dests=None):
    _rp_globals.set(g)
    tools = {k:(v if not callable(v) or _callable_ok(k,v) else _Uncallable(v,k))
        for k,v in g.items() if not k.startswith('_')}
    def unpack(a,*args): return list(a)
    builtins = dict(all_builtins)
    if ok_dests is not None:
        safe_open = _safe_open(ok_dests)
        builtins['open'] = safe_open
    rg = dict(__builtins__=builtins, _getattr_=_make_safe_getattr(ok_dests),
        _inplacevar_ = _inplacevar_, type = _safe_type,
        _getitem_=lambda o,k: o[k], _getiter_=iter, _apply_ = lambda f, *a, **kw: f(*a, **kw),
        _write_=_default_write_, __metaclass__=type, __name__='<tool>',
        _print_=_DirectPrint, _print=_DirectPrint(),
        _unpack_sequence_=unpack, _iter_unpack_sequence_=unpack,
        enumerate=enumerate, sorted=sorted, reversed=reversed, max=max, min=min, **tools)
    if ok_dests is not None: rg['open'] = safe_open
    loc = {}
    async def run(src, is_exec=True):
        try:
            comp = compile_restricted(src, '<tool>', 'exec' if is_exec else 'eval', policy=SafeTransformer)
            r = eval(comp, rg, loc)
            return (await r) if inspect.isawaitable(r) else r
        except NameError as e: raise NameError(f'`{e.name}` is has not been added to this sandbox yet') from None
        except SyntaxError as e:
            if isinstance(e.msg, tuple): raise SyntaxError('\n'.join(e.msg)) from None
            raise
    tree = ast.parse(code)
    warnings.filterwarnings('ignore', category=SyntaxWarning)
    res = None
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        last = tree.body.pop()
        if tree.body: await run(ast.unparse(ast.Module(tree.body, [])))
        res = await run(ast.unparse(ast.Expression(last.value)), False)
    else: await run(code)
    g.update({k:v for k,v in loc.items() if not k.startswith('_') and (k not in g or k.endswith('_'))})
    return res

# %% ../nbs/00_core.ipynb #5d38a1d0
default_ok_dests = None

# %% ../nbs/00_core.ipynb #5447b52c
class RunPython:
    def __init__(self, g=None, sentinel=None, ok_dests=UNSET):
        if ok_dests is UNSET: ok_dests = default_ok_dests
        self.g = _find_frame_dict(sentinel) if g is None else g
        self.ok_dests = ok_dests

    @property
    def __doc__(self):
        def _cls_name(o): return getattr(o, '__name__', None) or getattr(o, '__qualname__', str(o))
        def _meth_name(m): return m[0] if isinstance(m, tuple) else m
        all_names = set(__llmtools__)
        for ms in __pytools__.values():
            for m in ms:
                n = _meth_name(m)
                if n is not ...: all_names.add(n)
        tools = ', '.join(sorted(all_names))
        meths = '; '.join(f"`{_cls_name(c)}`: {', '.join(sorted(str(_meth_name(m)) for m in ms if _meth_name(m) is not ...))}" if ... not in ms
                          else f"`{_cls_name(c)}`: *" for c,ms in sorted(__pytools__.items(), key=lambda x: _cls_name(x[0])) if ms)
        meths_s = f'\n\n            Allowed methods by type: {meths}' if meths else ''
        return f"""Execute restricted Python with access to LLM tools, returning last expression.
            `import` works in the usual way. All non-callable globals and non-callable attrs are usable.
            Callable globals are usable only if explicitly registered as tools.
            Callable object attrs are only accessible if `ClassName.method` is registered as a tool.
            Multiline code blocks can be used, including defining functions and variables, for use within the call.
            In addition most builtins are available, plus these symbols: {tools}{meths_s}

            **NB**: If `code` creates symbols that end with `_`, they will be exported by to the calling namespace.
            - This is how you can use symbols that either human or AI can use again later.
            Examples: `len([1,2,3])` (builtin); `add_msg(content="hi")` (tool); `df.shape` (non-callable attr);
            `[x**2 for x in range(5)]` (last expression returned); `sorted(my_dict.items())` (builtin + non-callable attr)"""

    async def __call__(self, code:str): return await _run_python(code, g=self.g, ok_dests=self.ok_dests)

# %% ../nbs/00_core.ipynb #9105f690
def create_pyrun_magic(shell=None, pyrun=None):
    "Create magic"
    if not shell: shell = get_ipython()
    if not pyrun: pyrun = RunPython()
    def f(line, cell=None):
        if line=='-o': return pyrun
        if not cell: return
        return pyrun(cell)
    shell.register_magic_function(f, 'line_cell', 'py')

# %% ../nbs/00_core.ipynb #d2e5b93e
allow_write_types(dict, list, SimpleNamespace)

# %% ../nbs/00_core.ipynb #b27c499a
def doc(sym  # Symbol to retrieve docs for
)->str:
    """Get documentation (signature, docstring, + docments if they exist) for `sym`.
    **NB**: This is not an llm tool, so must be run with `%%py` or `pyrun()`. `sym` must be available in the namespace."""
    return str(MarkdownRenderer(sym))

# %% ../nbs/00_core.ipynb #1d75894f
from io import TextIOWrapper,BufferedWriter,BufferedRandom,FileIO

# %% ../nbs/00_core.ipynb #2c753931
_file_meths = ['read','readline','readlines','write','writelines','seek','tell','close','flush']
allow({TextIOWrapper: _file_meths, BufferedWriter: _file_meths, BufferedRandom: _file_meths, FileIO: _file_meths})

# %% ../nbs/00_core.ipynb #67713a82
allow({
    re: ..., math: ..., collections: ..., copy: ...,
    tuple: ..., float: ..., str: ..., bytes: ..., int: ..., frozenset: ...,
    Counter: ..., itertools: ..., functools: ..., textwrap: ...,
    datetime: ..., dt_mod: ..., operator: ...,
    StringIO: ..., BytesIO: ..., dict: ..., list: ..., set: ...,
    json: ['loads', 'dumps', 'load'],
    Path: ['expanduser', 'read_text', 'glob', 'iterdir', 'exists', 'read_bytes', 'is_file', 'is_dir', 'stat', 'resolve',
        'with_suffix', 'with_name', 'relative_to', 'match', 'joinpath'],
    asyncio: ['gather','sleep'], httpx: ['get', 'options'],
    },
    urlencode, quote, unquote, display, HTML, Markdown, Image, Pretty, SVG, doc
)


# %% ../nbs/00_core.ipynb #67b9faa7
allow({
    os.path: ..., base64: ..., hashlib: ..., random: ..., statistics: ..., difflib: ...,
    heapq: ..., bisect: ..., html: ..., struct: ..., fnmatch: ..., time: ..., deque: ...,
    urllib.parse: ..., dataclasses: ..., shlex: ..., zlib: ..., unicodedata: ..., binascii: ...,
    enum: ..., secrets: ..., ast: ..., inspect: ..., keyword: ...,
    ipaddress: ..., colorsys: ..., cmath: ..., decimal: ..., fractions: ...,
    uuid: ..., pprint: ..., types: ..., traceback: ..., warnings: ..., Pattern: ...,
    csv: ['reader', 'DictReader'],
    pickle: ['loads', 'dumps'],
    contextlib: ['suppress', 'contextmanager'],
    ET: ['fromstring', 'tostring'],
    ET.Element: ['findall', 'find', 'get', 'iter'],
    sys: ['getsizeof'],
})

# %% ../nbs/00_core.ipynb #2324abe0
_path_wp = PathWritePolicy()
_dst1 = PosWritePolicy(1, 'dst')
_rename_wp = PathWritePolicy(target_pos=0, target_kw='target')

allow({
    Path: ['write_text', 'write_bytes', 'mkdir', 'touch', 'unlink', 'rmdir', 'chmod', 'symlink_to', 'hardlink_to'],
}, write_policy=_path_wp)
allow({Path: [('rename', _rename_wp), ('replace', _rename_wp)]})
allow({
    shutil: ['copy', 'copy2', 'copytree', 'move'],
}, write_policy=_dst1)
allow({shutil: [('rmtree', PosWritePolicy(0, 'path'))]})


# %% ../nbs/00_core.ipynb #e2c7e67d
_cfg_py = xdg_config_home() / 'safepyrun' / 'config.py'
if _cfg_py.exists():
    try:
        _cfg_ns = {k:v for k,v in globals().items() if not k.startswith('_')}
        exec(_cfg_py.read_text(), _cfg_ns)
        if 'default_ok_dests' in _cfg_ns: globals()['default_ok_dests'] = _cfg_ns['default_ok_dests']
    except Exception as e: warnings.warn(f"Failed to load {_cfg_py}: {e}")

# %% ../nbs/00_core.ipynb #e67f14ce
def allow_matplotlib():
    import matplotlib.pyplot as plt
    from matplotlib.figure import Figure
    from matplotlib.axes import Axes
    from matplotlib.axis import Axis
    from matplotlib.spines import Spine, SpinesProxy

    allow({
        plt: ['plot','figure','axis', 'subplots', 'show', 'savefig', 'tight_layout', 'subplot', 'bar', 'scatter', 'hist',
            'xlabel', 'ylabel', 'title', 'legend', 'grid', 'xlim', 'ylim', 'colorbar', 'imshow'],
        Figure: ['savefig', 'tight_layout', 'set_size_inches', 'add_subplot', 'suptitle'],
        Axes: ['plot', 'bar', 'barh', 'scatter', 'hist', 'set_xlabel', 'set_ylabel', 'set_title',
            'legend', 'grid', 'set_xlim', 'set_ylim', 'tick_params', 'set_xticks', 'set_yticks',
            'annotate', 'text', 'axhline', 'axvline', 'fill_between', 'twinx', 'imshow', 'pie',
            'boxplot', 'errorbar', 'stem', 'loglog', 'semilogx', 'semilogy', 'set_xscale', 'set_yscale'],
        Axis: ['set_major_formatter', 'set_minor_formatter', 'set_major_locator', 'set_minor_locator'],
        Spine: ['set_visible'], SpinesProxy: ['set_visible'],
    })

    _savefig_wp = PosWritePolicy(0, 'fname')
    allow({Figure: [('savefig', _savefig_wp)], plt: [('savefig', _savefig_wp)]})


# %% ../nbs/00_core.ipynb #8d1cb417
def load_ipython_extension(ip):
    ns = ip.user_ns
    ns['pyrun'] = pyrun = RunPython(g=ns)
    ns['allow'] = allow
    create_pyrun_magic(ip, pyrun)
