# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_safer.ipynb.

# %% auto #0
__all__ = ['ALLOWED_DUNDERS', 'mon', 'default_ok_dests', 'find_var', 'should_export', 'SafeTransformer', 'on_call', 'before_deny',
           'srcfn', 'RunPython', 'create_pyrun_magic', 'allow_matplotlib']

# %% ../nbs/02_safer.ipynb #468aa264
from fastcore.utils import *
from fastcore.xtras import asdict
from fastcore.xdg import xdg_config_home
from fastcore.docments import MarkdownRenderer
from pyskills import *
from pyskills import __pytools__

from inspect import currentframe,Parameter,signature
from contextvars import ContextVar
from types import MappingProxyType

import linecache,builtins,inspect,types,subprocess

# %% ../nbs/02_safer.ipynb #f178e529
from fastcore.imports import __llmtools__
from fastcore.test import expect_fail,test_eq
from RestrictedPython import utility_builtins, safe_builtins,limited_builtins
from RestrictedPython.transformer import RestrictingNodeTransformer, INSPECT_ATTRIBUTES, copy_locations
from restrictedpython_async import *

# %% ../nbs/02_safer.ipynb #16c25d79
# ContextVar fallback for when stack walking fails (e.g. inside asyncio.gather)
_rp_globals = ContextVar('_rp_globals', default=None)

def _find_frame_dict(sentinel:str):
    "Find the globals dict containing sentinel, or calling frame's globals if no sentinel"
    frame = currentframe().f_back.f_back
    if not sentinel: return frame.f_globals
    while frame:
        if sentinel in frame.f_globals: return frame.f_globals
        frame = frame.f_back
    # Fall back to RunPython globals stored in ContextVar (e.g. from asyncio.gather)
    rpg = _rp_globals.get()
    if rpg and sentinel in rpg: return rpg
    return globals()


# %% ../nbs/02_safer.ipynb #99383e45
def find_var(var:str):
    "Search for var in all frames of the call stack"
    return _find_frame_dict(var)[var]

# %% ../nbs/02_safer.ipynb #b0f8587e
class _WriteGuard:
    "Proxy that allows item/attr mutation but blocks setting attrs to callables"
    def __init__(self, obj): object.__setattr__(self, '_obj', obj)
    def _chk_globals(self):
        o = object.__getattribute__(self, '_obj')
        if isinstance(o, dict) and '__builtins__' in o:
            raise PermissionError("Cannot mutate globals/frame dicts")
    def __setattr__(self, name, val):
        if callable(val): raise PermissionError(f"Setting attribute '{name}' to a callable is not allowed")
        setattr(object.__getattribute__(self, '_obj'), name, val)
    def __delattr__(self, name): delattr(object.__getattribute__(self, '_obj'), name)
    def __setitem__(self, key, val):
        self._chk_globals()
        object.__getattribute__(self, '_obj')[key] = val
    def __delitem__(self, key):
        self._chk_globals()
        del object.__getattribute__(self, '_obj')[key]

def _default_write_(obj):
    "Guard for in-place mutation; blocks setting attrs to callables"
    return _WriteGuard(obj)

# %% ../nbs/02_safer.ipynb #703cdc90
class _AllowChecked:
    "Wrap a method to enforce its WritePolicy before calling"
    def __init__(self, obj, method, policy, ok_dests): self.obj,self.method,self.policy,self.ok_dests = obj,method,policy,ok_dests
    def __call__(self, *args, **kwargs):
        self.policy(self.obj, args, kwargs, self.ok_dests)
        return self.method(*args, **kwargs)

# %% ../nbs/02_safer.ipynb #ac94dd1c
def _cls_ok(obj, name):
    for o in [obj] + list(type(obj).__mro__):
        try: s = __pytools__.get(o)
        except TypeError: continue
        if s and _name_in(s, name): return True
    return False

# %% ../nbs/02_safer.ipynb #b4b59376
def _get_policy(s, name):
    for x in s:
        if isinstance(x, tuple) and x[0] == name: return x[1]
    return None

def _get_write_policy(obj, name):
    for o in [obj] + list(type(obj).__mro__):
        try: s = __pytools__.get(o)
        except TypeError: continue
        if s:
            p = _get_policy(s, name)
            if p is not None: return p
    return None

# %% ../nbs/02_safer.ipynb #6becac3b
class _DirectPrint:
    def __init__(self, *a, **kw): pass
    def _call_print(self, *a, **kw): print(*a, **kw)
    def __call__(self, *a, **kw): print(*a, **kw)

# %% ../nbs/02_safer.ipynb #6eeed34a
def _callable_ok(k, v):
    try:
        if v in __pytools__: return True
    except TypeError: pass
    if k in __llmtools__: return True
    if any(c in __pytools__ for c in type(v).__mro__): return True
    mod = sys.modules.get(getattr(v, '__module__', None))
    if mod and _cls_ok(mod, getattr(v, '__qualname__', k)): return True
    if (s:=getattr(v, '__self__', None)) and _cls_ok(s, getattr(v, '__func__', v).__name__): return True
    return False

# %% ../nbs/02_safer.ipynb #ac009f17
_inplace_ops = {
    '+=': operator.iadd, '-=': operator.isub, '*=': operator.imul,
    '/=': operator.itruediv, '//=': operator.ifloordiv, '%=': operator.imod,
    '**=': operator.ipow, '<<=': operator.ilshift, '>>=': operator.irshift,
    '&=': operator.iand, '|=': operator.ior, '^=': operator.ixor,
    '@=': operator.imatmul,
}

def _inplacevar_(op, x, y): return _inplace_ops[op](x, y)

# %% ../nbs/02_safer.ipynb #5327ac1d
def should_export(k, v, g):
    "True if sandbox local `k` with value `v` should be exported back to caller globals `g`"
    if k.startswith('_'): return False
    if k.endswith('_'): return True
    return not (k in g and (callable(v) or isinstance(v, types.ModuleType)))

# %% ../nbs/02_safer.ipynb #c1555a38
ALLOWED_DUNDERS = {'__name__', '__module__', '__doc__', '__qualname__', '__file__'}

class SafeTransformer(RestrictingNodeTransformer):
    def visit_Expr(self, node):
        if isinstance(node.value, ast.Constant): return node
        return super().visit_Expr(node)
    def visit_Attribute(self, node):
        if node.attr.startswith('_') and node.attr != '_' and node.attr not in ALLOWED_DUNDERS:
            self.error(node, f'"{node.attr}" is an invalid attribute name because it starts with "_".')
        if node.attr.endswith('__roles__'):
            self.error(node, f'"{node.attr}" is an invalid attribute name because it ends with "__roles__".')
        if node.attr in INSPECT_ATTRIBUTES:
            self.error(node, f'"{node.attr}" is a restricted name, that is forbidden to access in RestrictedPython.')
        if isinstance(node.ctx, ast.Load):
            node = self.node_contents_visit(node)
            new_node = ast.Call(func=ast.Name('_getattr_', ast.Load()), args=[node.value, ast.Constant(node.attr)], keywords=[])
            copy_locations(new_node, node)
            return new_node
        elif isinstance(node.ctx, (ast.Store, ast.Del)):
            node = self.node_contents_visit(node)
            new_value = ast.Call(func=ast.Name('_write_', ast.Load()), args=[node.value], keywords=[])
            copy_locations(new_value, node.value)
            node.value = new_value
            return node
        else: raise NotImplementedError(f"Unknown ctx type: {type(node.ctx)}")
    def visit_AnnAssign(self, node): return self.node_contents_visit(node)

# %% ../nbs/02_safer.ipynb #14a70f13
from fastaudit import *

# %% ../nbs/02_safer.ipynb #2b3a8099
mon = sys.monitoring
def on_call(caller, callee, fn, code, off, data):
    if callee.startswith(('numpy.',)) or callee.endswith(('.dumps','.loads')):
        return mon.DISABLE

# %% ../nbs/02_safer.ipynb #ae19467f
def before_deny(event, args, frame, msg, data):
    pytools,ok_dests = data['pytools'],data['ok_dests']

    def _frame_args(fr, obj=None):
        c = fr.f_code
        n,nkw = c.co_argcount,c.co_kwonlyargcount
        args = [fr.f_locals[o] for o in c.co_varnames[:n] if o in fr.f_locals]
        if obj is not None and args and args[0] is obj: args = args[1:]
        kw = {o:fr.f_locals[o] for o in c.co_varnames[n:n+nkw] if o in fr.f_locals}
        i = n+nkw
        if c.co_flags & inspect.CO_VARARGS:
            args += list(fr.f_locals.get(c.co_varnames[i], ()))
            i += 1
        if c.co_flags & inspect.CO_VARKEYWORDS: kw.update(fr.f_locals.get(c.co_varnames[i], {}))
        return args,kw

    def _check(s, name, fr, obj=None):
        if ... in s or name in s: return True
        for x in s:
            if isinstance(x, tuple) and x[0] == name:
                a,kw = _frame_args(fr, obj)
                x[1](obj, a, kw, ok_dests)
                return True
        return False

    fr = frame
    while fr:
        mod = sys.modules.get(fr.f_globals.get('__name__'))
        qn,nm = fr.f_code.co_qualname,fr.f_code.co_name
        if mod in pytools and _check(pytools[mod], nm, fr): return True
        if mod and '.' in qn:
            cls = getattr(mod, qn.rsplit('.', 1)[0], None)
            for o in [cls] + list(getattr(cls, '__mro__', ())):
                if o in pytools and _check(pytools[o], nm, fr, fr.f_locals.get('self')): return True
        fr = fr.f_back

# %% ../nbs/02_safer.ipynb #12b831de
def srcfn(src):
    "Stores src in linecache under <pyrun_{i%10}>, returns the name." 
    linecache.cache[fn] = (len(src), None,  src.splitlines(keepends=True), fn:=f'<pyrun_{srcfn.i}>')
    srcfn.i = (srcfn.i + 1)%10
    return fn
srcfn.i=0

# %% ../nbs/02_safer.ipynb #b6724773
def _safe_import(name, globals=None, locals=None, fromlist=(), level=0):
    if name not in sys.modules: raise PermissionError(f"{name} not preloaded")
    if not fromlist: return __import__(name, globals=globals, locals=locals, level=level)
    return SimpleNamespace(**{n:rg['_getattr_'](mod, n) for n in fromlist})

_builtins = dict(builtins.__dict__) | dict(__import__ = _safe_import)

# %% ../nbs/02_safer.ipynb #b1de0b53
async def _run_python(code:str, g=None, ok_dests=None):
    _rp_globals.set(g)
    data = dict(pytools=MappingProxyType({k:frozenset(v) for k,v in __pytools__.items()}),
        ok_dests=ok_dests or ())
    with mk_audit(ok_dests, before_deny=before_deny, data=data, on_call=on_call)():
        return await __run_python(code=code, g=g, ok_dests=ok_dests)

# %% ../nbs/02_safer.ipynb #55cc6157
async def __run_python(code:str, g=None, ok_dests=None):
    _rp_globals.set(g)
    def unpack(a,*args): return list(a)
    rg =g | dict(__builtins__=_builtins, _getattr_=getattr, _inplacevar_ = _inplacevar_, type = type,
        _getitem_=lambda o,k: o[k], _getiter_=iter, _apply_ = lambda f, *a, **kw: f(*a, **kw),
        _write_=_default_write_, __metaclass__=type, __name__='<pyrun>',
        _print_=_DirectPrint, _print=_DirectPrint(),
        _unpack_sequence_=unpack, _iter_unpack_sequence_=unpack)
    loc = {}
    async def run(src, is_exec=True):
        try:
            comp = compile_restricted(src, srcfn(src), 'exec' if is_exec else 'eval', policy=SafeTransformer)
            r = eval(comp, rg, loc)
            return (await r) if inspect.isawaitable(r) else r
        except SyntaxError as e:
            if isinstance(e.msg, tuple): raise SyntaxError('\n'.join(e.msg)) from None
            raise
    tree = ast.parse(code)
    warnings.filterwarnings('ignore', category=SyntaxWarning)
    res = None
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        last = tree.body.pop()
        if tree.body: await run(ast.unparse(ast.Module(tree.body, [])))
        res = await run(ast.unparse(ast.Expression(last.value)), False)
    else: await run(code)
    g.update(filter_dict(loc, lambda k,v: should_export(k, v, g)))
    return res

# %% ../nbs/02_safer.ipynb #5d38a1d0
default_ok_dests = ()

# %% ../nbs/02_safer.ipynb #5447b52c
class RunPython:
    """Execute restricted Python with access to LLM tools, returning last expression.
    `import` works in the usual way. All builtins are available.
    Multiline code blocks can be used, including defining functions and variables, for use within the call.

    **NB**: Locals are exported back to the caller's namespace unless they'd shadow an existing callable or module.
    - Symbols ending with `_` are always exported, even if they shadow existing names.
    Examples: `len([1,2,3])` (builtin); `add_msg(content="hi")` (tool); `df.shape` (non-callable attr);
    `[x**2 for x in range(5)]` (last expression returned); `sorted(my_dict.items())` (builtin + non-callable attr)"""

    def __init__(self, g=None, sentinel=None, ok_dests=UNSET):
        if ok_dests is UNSET: ok_dests = default_ok_dests
        self.g = _find_frame_dict(sentinel) if g is None else g
        self.ok_dests = ok_dests or ()

    async def __call__(self, code:str):
        try: return await _run_python(code, g=self.g, ok_dests=self.ok_dests)
        except Exception as e:
            tb = e.__traceback__
            while tb.tb_next and not tb.tb_frame.f_code.co_filename.startswith('<pyrun'): tb = tb.tb_next
            raise e.with_traceback(tb) from None

# %% ../nbs/02_safer.ipynb #9105f690
def create_pyrun_magic(shell=None, pyrun=None):
    "Create magic"
    if not shell: shell = get_ipython()
    if not pyrun: pyrun = RunPython()
    def f(line, cell=None):
        if line=='-o': return pyrun
        if not cell: return
        return pyrun(cell)
    shell.register_magic_function(f, 'line_cell', 'py')

# %% ../nbs/02_safer.ipynb #2324abe0
_path_wp = PathWritePolicy()
_dst1 = PosAllowPolicy(1, 'dst')
_rename_wp = PathWritePolicy(target_pos=0, target_kw='target')

# %% ../nbs/02_safer.ipynb #e2c7e67d
_cfg_py = xdg_config_home() / 'safepyrun' / 'config.py'
if _cfg_py.exists():
    try:
        _cfg_ns = {k:v for k,v in globals().items() if not k.startswith('_')}
        exec(_cfg_py.read_text(), _cfg_ns)
        # TODO: Need to update this for the new set-data/allow API
        if 'default_ok_dests' in _cfg_ns: globals()['default_ok_dests'] = _cfg_ns['default_ok_dests']
    except Exception as e: warnings.warn(f"Failed to load {_cfg_py}: {e}")

# %% ../nbs/02_safer.ipynb #92e10e61
def allow_matplotlib():
    import matplotlib.pyplot as plt
    from matplotlib.figure import Figure
    from matplotlib.axes import Axes
    from matplotlib.axis import Axis
    from matplotlib.spines import Spine, SpinesProxy
    from matplotlib.backend_bases import FigureCanvasBase
    from matplotlib.font_manager import FontManager
    from matplotlib.transforms import Bbox

    allow(Bbox.update_from_path, FigureCanvasBase.__init__, FontManager.findfont)
    allow({
        plt: ['plot','figure','axis', 'subplots', 'show', 'tight_layout', 'subplot', 'bar', 'scatter', 'hist',
            'xlabel', 'ylabel', 'title', 'legend', 'grid', 'xlim', 'ylim', 'colorbar', 'imshow'],
        Figure: ['tight_layout', 'set_size_inches', 'add_subplot', 'suptitle'],
        Axes: ['plot', 'bar', 'barh', 'scatter', 'hist', 'set_xlabel', 'set_ylabel', 'set_title',
            'legend', 'grid', 'set_xlim', 'set_ylim', 'tick_params', 'set_xticks', 'set_yticks',
            'annotate', 'text', 'axhline', 'axvline', 'fill_between', 'twinx', 'imshow', 'pie',
            'boxplot', 'errorbar', 'stem', 'loglog', 'semilogx', 'semilogy', 'set_xscale', 'set_yscale'],
        Axis: ['set_major_formatter', 'set_minor_formatter', 'set_major_locator', 'set_minor_locator'],
        Spine: ['set_visible'], SpinesProxy: ['set_visible'],
    })

    _savefig_wp = PosAllowPolicy(0, 'fname')
    allow({Figure: [('savefig', _savefig_wp)], plt: [('savefig', _savefig_wp)]})

# %% ../nbs/02_safer.ipynb #8d1cb417
# def load_ipython_extension(ip):
#     ns = ip.user_ns
#     ns['pyrun'] = pyrun = RunPython(g=ns)
#     ns['allow'] = allow
#     create_pyrun_magic(ip, pyrun)

# %% ../nbs/02_safer.ipynb #30964442
# from fastcore.script import call_parse, Param

# %% ../nbs/02_safer.ipynb #74c49b7c
# @call_parse
# def cli(path: Param("Path to script, or '-' for stdin", str, opt=False, nargs='?', default='-')):
#     "Run a python script file in the safepyrun sandbox"
#     try:
#         code = sys.stdin.read() if path == '-' else Path(path).read_text()
#         if (r := asyncio.run(RunPython()(code))) is not None: print(r)
#     except Exception as e: return not print(f"Error: {e}", file=sys.stderr)
